# -*- coding: utf-8 -*-
"""Control structures Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-PwjpH5oGldYHlw2Qwc4VN45RMaPHVp5

Task 1: Check if a Number is Even or Odd
Problem Statement:  Write a Python program that:
1. 	Takes an integer input from the user.
2. 	Checks whether the number is even or odd using an if-else statement.
3. 	Displays the result accordingly.
"""

try:
  userInput = int(input("Enter the number: "))
  if(userInput % 2 == 0):
    print(f'{userInput} is an even number')
  else:
    print(f'{userInput} is an odd number')
except ZeroDivisionError:
  print("You cannot enter other number than zero")
except ValueError:
  print("Please enter valid number")

"""Task 2: Sum of Integers from 1 to 50 Using a Loop

Problem Statement: Write a Python program that:
1.   Uses a for loop to iterate over numbers from 1 to 50.
2.   Calculates the sum of all integers in this range.
3.   Displays the final sum.

"""

sum=0
for i in range(51):
  sum= sum+ i
print(f"The sum of numbers from 1 to 50 is {sum}")